name: A workflow for DevOp Coursework
on: push

jobs:
  build:
    name: DevOp Coursework
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup network
        run:
          docker network create --driver bridge gp-bridge
      - name: Build with Maven
        run: mvn package
      - name: Build
        run: docker build -t gp_devops .
      - name: Run image
        run: docker run --network gp-bridge --name semcontainer gp_devops
      - name: view logs
        run: docker logs semcontainer